"""Exercises scripts/generate-control-center-data.py against the real
Control Center v1 contract fixtures and ui/control-center/sample-fleet.json
(issue #211). Loaded by file path via importlib because the script's
filename has hyphens (not a valid module name)."""
import importlib.util
import json
import os
import tempfile
import unittest
from pathlib import Path

from . import _pathfix  # noqa: F401  (sets sys.path)

_THIS = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS, "..", "..", ".."))
_SCRIPT_PATH = os.path.join(_REPO_ROOT, "scripts", "generate-control-center-data.py")

_spec = importlib.util.spec_from_file_location("generate_control_center_data", _SCRIPT_PATH)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


class TestGenerateControlCenterData(unittest.TestCase):
    def test_build_data_is_json_serializable_and_has_expected_sections(self):
        data = gen.build_data()
        # Must be plain JSON-serializable data - no functions/dates/etc.
        rendered = json.dumps(data)
        self.assertIsInstance(rendered, str)
        for key in (
            "servers", "hermesTree", "hermesMeta", "hermesEvents", "deployments",
            "jobsRunning", "queue", "health", "backupPolicy", "snapshots",
            "audit", "workers", "timeline", "kpis", "milestones", "issues",
        ):
            self.assertIn(key, data, f"missing section: {key}")

    def test_build_data_sources_servers_from_sample_fleet_json(self):
        data = gen.build_data()
        sample = gen.load_json(gen.SAMPLE_FLEET_PATH)
        expected_ids = sorted(s["id"] for s in sample["servers"])
        actual_ids = [s["id"] for s in data["servers"]]
        self.assertEqual(actual_ids, expected_ids)

    def test_render_is_deterministic_across_runs(self):
        first = gen.render(gen.build_data())
        second = gen.render(gen.build_data())
        self.assertEqual(first, second)

    def test_render_starts_with_the_autogenerated_header_and_sets_window_global(self):
        rendered = gen.render(gen.build_data())
        self.assertTrue(rendered.startswith("// ui/control-center/data.js"))
        self.assertIn("AUTO-GENERATED", rendered)
        self.assertIn("window.OMES_CC_DATA = {", rendered)
        self.assertTrue(rendered.rstrip().endswith(";"))

    def test_main_writes_a_file_that_then_passes_check(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "data.js"
            self.assertEqual(gen.main(["--out", str(out)]), 0)
            self.assertTrue(out.is_file())
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 0)

    def test_check_fails_on_a_stale_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "data.js"
            out.write_text("window.OMES_CC_DATA = {};\n", encoding="utf-8")
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 1)

    def test_check_fails_when_the_output_file_does_not_exist(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "missing" / "data.js"
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 1)

    def test_the_committed_data_js_is_up_to_date(self):
        # Guards against someone hand-editing ui/control-center/data.js or
        # a fixture/sample-fleet.json change landing without regenerating
        # it - the same thing --check protects in CI (tests/run.sh).
        committed = Path(_REPO_ROOT) / "ui" / "control-center" / "data.js"
        self.assertTrue(committed.is_file(), "ui/control-center/data.js is missing; run the generator")
        self.assertEqual(committed.read_text(encoding="utf-8"), gen.render(gen.build_data()))

    def test_hermes_tree_is_nested_from_the_flat_fixture(self):
        tree = gen.build_hermes_tree()
        self.assertGreaterEqual(len(tree["tree"]), 1)
        root = tree["tree"][0]
        self.assertIn("children", root)
        self.assertIsInstance(root["children"], list)


if __name__ == "__main__":
    unittest.main()
