"""Exercises scripts/generate-control-center-data.py against the real
Control Center v1 contract fixtures and ui/control-center/sample-fleet.json
(issue #211). Loaded by file path via importlib because the script's
filename has hyphens (not a valid module name)."""
import importlib.util
import json
import os
import tempfile
import unittest
from pathlib import Path

from . import _pathfix  # noqa: F401  (sets sys.path)

_THIS = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS, "..", "..", ".."))
_SCRIPT_PATH = os.path.join(_REPO_ROOT, "scripts", "generate-control-center-data.py")

_spec = importlib.util.spec_from_file_location("generate_control_center_data", _SCRIPT_PATH)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


class TestGenerateControlCenterData(unittest.TestCase):
    def test_build_data_is_json_serializable_and_has_expected_sections(self):
        data = gen.build_data()
        # Must be plain JSON-serializable data - no functions/dates/etc.
        rendered = json.dumps(data)
        self.assertIsInstance(rendered, str)
        for key in (
            "servers", "hermesTree", "hermesMeta", "hermesEvents", "deployments",
            "jobsRunning", "queue", "health", "backupPolicy", "snapshots",
            "audit", "workers", "timeline", "kpis", "milestones", "issues",
        ):
            self.assertIn(key, data, f"missing section: {key}")

    def test_build_data_sources_servers_from_sample_fleet_json(self):
        data = gen.build_data()
        sample = gen.load_json(gen.SAMPLE_FLEET_PATH)
        expected_ids = sorted(s["id"] for s in sample["servers"])
        actual_ids = [s["id"] for s in data["servers"]]
        self.assertEqual(actual_ids, expected_ids)

    def test_render_is_deterministic_across_runs(self):
        first = gen.render(gen.build_data())
        second = gen.render(gen.build_data())
        self.assertEqual(first, second)

    def test_render_starts_with_the_autogenerated_header_and_sets_window_global(self):
        rendered = gen.render(gen.build_data())
        self.assertTrue(rendered.startswith("// ui/control-center/data.js"))
        self.assertIn("AUTO-GENERATED", rendered)
        self.assertIn("window.OMES_CC_DATA = {", rendered)
        self.assertTrue(rendered.rstrip().endswith(";"))

    def test_main_writes_a_file_that_then_passes_check(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "data.js"
            self.assertEqual(gen.main(["--out", str(out)]), 0)
            self.assertTrue(out.is_file())
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 0)

    def test_check_fails_on_a_stale_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "data.js"
            out.write_text("window.OMES_CC_DATA = {};\n", encoding="utf-8")
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 1)

    def test_check_fails_when_the_output_file_does_not_exist(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "missing" / "data.js"
            self.assertEqual(gen.main(["--check", "--out", str(out)]), 1)

    def test_the_committed_data_js_is_up_to_date(self):
        # Guards against someone hand-editing ui/control-center/data.js or
        # a fixture/sample-fleet.json change landing without regenerating
        # it - the same thing --check protects in CI (tests/run.sh).
        committed = Path(_REPO_ROOT) / "ui" / "control-center" / "data.js"
        self.assertTrue(committed.is_file(), "ui/control-center/data.js is missing; run the generator")
        self.assertEqual(committed.read_text(encoding="utf-8"), gen.render(gen.build_data()))

    def test_hermes_tree_is_nested_from_the_flat_fixture(self):
        tree = gen.build_hermes_tree()
        self.assertGreaterEqual(len(tree["tree"]), 1)
        root = tree["tree"][0]
        self.assertIn("children", root)
        self.assertIsInstance(root["children"], list)

    # -- Finding 1: build_deployments() must not fabricate actor causality --

    def test_deployments_never_attribute_an_actor_to_an_unlinked_deployment(self):
        """The real fixtures currently have no genuine overlap between
        deployment.request and deployment-view targets (requests target
        srv-0001/dep-0001; views target server-acme-01/
        deployment-acme-hermes-01), so every generated row must fall back
        to the neutral placeholder "-" rather than an unrelated actor such
        as "user:operator-1"."""
        rows = gen.build_deployments()
        self.assertTrue(rows, "expected at least one deployment row")
        requests = gen.load_fixtures("deployment.request")
        real_targets = {
            (req["target"]["server_id"], req["target"]["deployment_id"])
            for req in requests
        }
        views = gen.load_fixtures("deployment-view")
        view_targets = {
            (view["target"]["server_id"], view["target"]["deployment_id"])
            for view in views
        }
        # Sanity: today's fixtures genuinely do not correlate. If this ever
        # trips, the fixtures gained real overlap and the "-" assertion
        # below should be revisited alongside it.
        self.assertEqual(real_targets & view_targets, set())
        for row in rows:
            self.assertEqual(
                row["who"], "-",
                f"deployment {row['id']!r} has no matching deployment.request "
                f"fixture but was attributed to {row['who']!r}",
            )

    def test_deployments_only_attribute_an_actor_that_shares_the_real_target_key(self):
        """Synthetic fixtures: a request and a view that share
        (server_id, deployment_id) must be correlated; a request for a
        different target must never leak onto an unrelated view, even when
        list/sort order would previously have paired them by index."""
        real_load_fixtures = gen.load_fixtures

        def fake_load_fixtures(schema_name):
            if schema_name == "deployment.request":
                return [
                    {
                        "actor": {"type": "user", "id": "operator-1"},
                        "target": {"server_id": "srv-unrelated", "deployment_id": "dep-unrelated"},
                    },
                    {
                        "actor": {"type": "service", "id": "control-center"},
                        "target": {"server_id": "server-acme-01", "deployment_id": "deployment-acme-hermes-01"},
                    },
                ]
            if schema_name == "deployment-view":
                return [
                    {
                        "tenant_id": "tenant-acme",
                        "target": {"server_id": "server-acme-01", "deployment_id": "deployment-acme-hermes-01"},
                        "desired_state": {"status": "running", "version": "1.5.0"},
                        "observed_state": {"status": "running", "version": "1.5.0"},
                        "last_reconciled_at": "2026-09-19T09:00:05Z",
                        "error_evidence": None,
                    },
                ]
            return real_load_fixtures(schema_name)

        gen.load_fixtures = fake_load_fixtures
        try:
            rows = gen.build_deployments()
        finally:
            gen.load_fixtures = real_load_fixtures

        self.assertEqual(len(rows), 1)
        # Correlated on the shared (server_id, deployment_id) key, not on
        # sorted-filename/list index position (which would have attributed
        # the first, unrelated "operator-1" request instead).
        self.assertEqual(rows[0]["who"], "service:control-center")

    # -- Finding 2: load_fixtures() must fail closed on a missing directory --

    def test_load_fixtures_raises_on_a_missing_fixture_directory(self):
        with self.assertRaises(FileNotFoundError):
            gen.load_fixtures("this-schema-does-not-exist")

    def test_load_fixture_and_load_fixtures_fail_the_same_way(self):
        """Both loaders must fail loudly (not silently degrade) when their
        backing fixtures are absent, so a renamed/removed schema directory
        fails the generator and its --check gate instead of silently
        zeroing out a UI section."""
        with self.assertRaises(FileNotFoundError):
            gen.load_fixture("this-schema-does-not-exist")
        with self.assertRaises(FileNotFoundError):
            gen.load_fixtures("this-schema-does-not-exist")


if __name__ == "__main__":
    unittest.main()
