#!/usr/bin/env bats
# tests/integration/graphify-export.bats - `omes graphify export` end to
# end against bin/omes, executing the real lib/omes/py/graphify/cli.py
# (issue #53). Requires a real system python3 - unlike
# tests/integration/graphify.bats (which fakes python3 purely to satisfy
# modules/graphify/module.sh's version-gate check), this suite needs the
# stdlib json/hashlib modules to actually run, so it never prepends a
# fake python3 shim onto PATH.
#
# Two render paths are exercised (docs/graphify.md §5.1/§5.2):
#   - "upstream" (the DEFAULT here, since tests/shims/graphify is always
#     on PATH and its `export obsidian` succeeds by default) - most tests
#     below exercise this path, matching what a real host with graphify
#     installed will actually do.
#   - "fallback" (OMES's own graph.json renderer) - forced via
#     SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL=1, simulating either upstream
#     failing or graphify not being installed at all (both collapse into
#     the same fallback code path in lib/omes/cmd/graphify.sh - see its
#     _graphify_stage_upstream_export comment).

setup() {
  load '../test_helper.bash'
  omes_test_setup
  OMES_BIN="${OMES_TEST_ROOT}/bin/omes"

  export HOME="${OMES_TEST_TMPDIR}/home"
  mkdir -p "$HOME"

  unset OBSIDIAN_VAULT_PATH OMES_GRAPHIFY_VAULT_SUBDIR OMES_GRAPHIFY_PROJECT_NAME \
    SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL || true

  FIXTURES="${OMES_TEST_ROOT}/tests/fixtures/graphify"

  # Work on private copies so tests never mutate the checked-in fixtures.
  WORK="${OMES_TEST_TMPDIR}/work"
  mkdir -p "$WORK"
  cp -r "${FIXTURES}/sample-repo" "${WORK}/sample-repo"
  OUT_DIR="${WORK}/sample-repo/graphify-out"

  VAULT_EMPTY="${WORK}/vault-empty"
  cp -r "${FIXTURES}/sample-vault-empty" "$VAULT_EMPTY"

  VAULT_POPULATED="${WORK}/vault-populated"
  cp -r "${FIXTURES}/sample-vault-populated" "$VAULT_POPULATED"
}

teardown() {
  omes_test_teardown
}

# ---------------------------------------------------------------------------
# Default (upstream `graphify export obsidian`) render path
# ---------------------------------------------------------------------------

@test "dry-run lists planned writes and writes nothing" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --dry-run
  [ "$status" -eq 0 ]
  [ -z "$(find "${VAULT_EMPTY}/graphify" -mindepth 1 2>/dev/null)" ]
}

@test "populated vault: export writes only under the OMES subdir, unrelated notes untouched byte-for-byte" {
  local before_sum
  before_sum="$(sha256sum "${VAULT_POPULATED}/My Personal Note.md" | awk '{print $1}')"

  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_POPULATED" --yes
  [ "$status" -eq 0 ]

  local after_sum
  after_sum="$(sha256sum "${VAULT_POPULATED}/My Personal Note.md" | awk '{print $1}')"
  [ "$before_sum" = "$after_sum" ]

  [ -f "${VAULT_POPULATED}/graphify/sample-repo/app.py.md" ]
}

@test "empty vault: export produces upstream's note carrying the injected omes_generated marker" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  local note="${VAULT_EMPTY}/graphify/sample-repo/app.py.md"
  [ -f "$note" ]
  run grep -c "omes_generated: true" "$note"
  [ "$output" -ge 1 ]
  # Upstream's own fields survive untouched alongside ours.
  run grep -c 'source_file: "src/app.py"' "$note"
  [ "$output" -ge 1 ]
  run grep -c "graphify_version" "$note"
  [ "$output" -ge 1 ]
  run grep -c "graph_sha256" "$note"
  [ "$output" -ge 1 ]
}

@test "upstream's non-Markdown outputs (canvas, nested .obsidian/graph.json) are copied through" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/graph.canvas" ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/.obsidian/graph.json" ]
}

@test "re-export overwrites its own previously-written non-Markdown files without conflict" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  omes_run_stdout_only "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes --json
  [ "$status" -eq 0 ]
  # No conflicts reported on the second run.
  run python3 -c 'import json,sys; d=json.load(sys.stdin); sys.exit(0 if d["result"]["conflicts"] == [] else 1)' <<< "$output"
  [ "$status" -eq 0 ]
}

@test "user-authored collision at a Markdown target path is refused, not overwritten" {
  mkdir -p "${VAULT_EMPTY}/graphify/sample-repo"
  printf '# Not generated by OMES\n' > "${VAULT_EMPTY}/graphify/sample-repo/app.py.md"

  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes --json
  [ "$status" -eq 0 ]

  run grep -c "Not generated by OMES" "${VAULT_EMPTY}/graphify/sample-repo/app.py.md"
  [ "$output" -eq 1 ]
}

@test "missing vault is refused without --init-vault" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "${WORK}/does-not-exist" --yes
  [ "$status" -ne 0 ]
  [ ! -d "${WORK}/does-not-exist" ]
}

@test "--init-vault creates a new vault and never invents .obsidian content beyond a marker directory" {
  local new_vault="${WORK}/brand-new-vault"
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$new_vault" --init-vault --yes
  [ "$status" -eq 0 ]
  [ -d "${new_vault}/.obsidian" ]
  [ -f "${new_vault}/graphify/sample-repo/app.py.md" ]
}

@test "vault without .obsidian/ is refused without --init-vault" {
  local plain_dir="${WORK}/plain-dir"
  mkdir -p "$plain_dir"
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$plain_dir" --yes
  [ "$status" -ne 0 ]
}

@test ".obsidian/ directory at the vault ROOT is never touched" {
  local before_sum
  before_sum="$(sha256sum "${VAULT_POPULATED}/.obsidian/app.json" | awk '{print $1}')"
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_POPULATED" --yes
  [ "$status" -eq 0 ]
  local after_sum
  after_sum="$(sha256sum "${VAULT_POPULATED}/.obsidian/app.json" | awk '{print $1}')"
  [ "$before_sum" = "$after_sum" ]
}

@test "OBSIDIAN_VAULT_PATH env var is honored when --vault is omitted" {
  OBSIDIAN_VAULT_PATH="$VAULT_EMPTY" run "$OMES_BIN" graphify export "$OUT_DIR" --yes
  [ "$status" -eq 0 ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/app.py.md" ]
}

@test "vault path is never guessed - missing both --vault and OBSIDIAN_VAULT_PATH is a usage error" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --yes
  [ "$status" -eq 2 ]
}

@test "missing graphify-out directory is refused" {
  run "$OMES_BIN" graphify export "${WORK}/does-not-exist" --vault "$VAULT_EMPTY" --yes
  [ "$status" -ne 0 ]
}

@test "missing graph.json inside an existing directory is refused" {
  mkdir -p "${WORK}/empty-out"
  run "$OMES_BIN" graphify export "${WORK}/empty-out" --vault "$VAULT_EMPTY" --yes
  [ "$status" -ne 0 ]
}

@test "export backs up the target subdir before writing and rollback restores it" {
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]

  # Simulate an operator hand-edit of a generated note before a re-export.
  printf 'tampered\n' >> "${VAULT_EMPTY}/graphify/sample-repo/app.py.md"

  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  run grep -c "tampered" "${VAULT_EMPTY}/graphify/sample-repo/app.py.md"
  [ "$status" -ne 0 ] || [ "$output" -eq 0 ]

  run "$OMES_BIN" graphify export rollback --yes
  [ "$status" -eq 0 ]
  run grep -c "tampered" "${VAULT_EMPTY}/graphify/sample-repo/app.py.md"
  [ "$output" -ge 1 ]
}

@test "--json emits a single JSON object on stdout" {
  omes_run_stdout_only "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes --json
  [ "$status" -eq 0 ]
  printf '%s' "$output" | python3 -m json.tool >/dev/null
}

# ---------------------------------------------------------------------------
# Fallback render path (upstream unavailable/failing)
# ---------------------------------------------------------------------------

@test "fallback: when upstream export obsidian fails, OMES renders directly from graph.json" {
  export SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL=1
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/_index.md" ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/_provenance.md" ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/src__app.py.md" ]
}

@test "fallback: generated notes carry the required front matter fields" {
  export SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL=1
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes
  [ "$status" -eq 0 ]
  local note="${VAULT_EMPTY}/graphify/sample-repo/src__app.py.md"
  [ -f "$note" ]
  run grep -c "omes_generated: true" "$note"
  [ "$output" -ge 1 ]
  run grep -c 'source: "src/app.py"' "$note"
  [ "$output" -ge 1 ]
}

@test "fallback: user-authored collision is refused, other notes still written" {
  export SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL=1
  mkdir -p "${VAULT_EMPTY}/graphify/sample-repo"
  printf '# Not generated by OMES\n' > "${VAULT_EMPTY}/graphify/sample-repo/_index.md"

  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_EMPTY" --yes --json
  [ "$status" -eq 0 ]

  run grep -c "Not generated by OMES" "${VAULT_EMPTY}/graphify/sample-repo/_index.md"
  [ "$output" -eq 1 ]
  [ -f "${VAULT_EMPTY}/graphify/sample-repo/_provenance.md" ]
}

@test "fallback: unrelated existing files in a populated vault stay untouched" {
  export SHIM_GRAPHIFY_EXPORT_OBSIDIAN_FAIL=1
  local before_sum
  before_sum="$(sha256sum "${VAULT_POPULATED}/My Personal Note.md" | awk '{print $1}')"
  run "$OMES_BIN" graphify export "$OUT_DIR" --vault "$VAULT_POPULATED" --yes
  [ "$status" -eq 0 ]
  local after_sum
  after_sum="$(sha256sum "${VAULT_POPULATED}/My Personal Note.md" | awk '{print $1}')"
  [ "$before_sum" = "$after_sum" ]
}
