// ui/control-center/data.js
// AUTO-GENERATED by scripts/generate-control-center-data.py - DO NOT EDIT BY HAND.
//
// Regenerate with:
//   python3 scripts/generate-control-center-data.py
//
// Sourced from contracts/control-center/v1/fixtures/*/valid-*.json (the
// same fixtures scripts/check-contracts.py validates) plus
// ui/control-center/sample-fleet.json (a small supplementary sample for
// fleet telemetry that has no v1 contract fixture yet). See that script's
// module docstring for exactly which fixtures feed which section.
//
// This is reference/prototype data for ui/control-center/index.html
// (issue #211). The functional Control Center screens are NOT
// implemented yet (tracked in #200/#201) - this file only feeds a static
// UI/UX prototype.
window.OMES_CC_DATA = {
  "audit": [
    {
      "act": "payment.succeeded",
      "actor": "svc/outbox",
      "ip": "-",
      "obj": "evt-payment-succeeded-00000001",
      "ok": true,
      "role": "system",
      "t": "2026-02-01T00:00:00Z"
    },
    {
      "act": "payment.succeeded",
      "actor": "provider/provider-primary",
      "ip": "-",
      "obj": "delivery-00000001",
      "ok": true,
      "role": "webhook",
      "t": "2026-02-01T00:00:02Z"
    }
  ],
  "backupPolicy": [
    {
      "k": "Status",
      "v": "completed"
    },
    {
      "k": "Target",
      "v": "srv-0001"
    },
    {
      "k": "Manifest",
      "v": "aaaaaaaaaaaaaaaa..."
    }
  ],
  "deployments": [
    {
      "env": "tenant-acme",
      "hosts": "server-acme-01",
      "id": "deployment-acme-hermes-01",
      "mod": "version 1.4.0",
      "pct": 100,
      "state": "ok",
      "when": "2026-09-19T08:00:05Z",
      "who": "-"
    },
    {
      "env": "tenant-acme",
      "hosts": "server-acme-01",
      "id": "deployment-acme-hermes-01",
      "mod": "version 1.5.0",
      "pct": 60,
      "state": "rollback",
      "when": "2026-09-19T09:00:05Z",
      "who": "-"
    }
  ],
  "health": [
    {
      "detail": "Telegram long-poll connected",
      "name": "Channel",
      "res": "pass"
    },
    {
      "detail": "gateway responds to health check",
      "name": "Gateway",
      "res": "pass"
    },
    {
      "detail": "host is reachable over SSH",
      "name": "Host",
      "res": "pass"
    },
    {
      "detail": "systemd unit is active",
      "name": "Runtime",
      "res": "pass"
    }
  ],
  "hermesEvents": [
    {
      "a": "sub-lead-001",
      "k": "tool",
      "m": "Delegated sub-tasks to child agents",
      "t": "2026-09-21T12:00:00Z"
    },
    {
      "a": "sub-code-001",
      "k": "tool",
      "m": "Started analysis of index definitions",
      "t": "2026-09-21T12:00:00Z"
    },
    {
      "a": "sub-child-001",
      "k": "ok",
      "m": "ShellCheck and lint passed cleanly",
      "t": "2026-09-21T12:01:00Z"
    },
    {
      "a": "sub-child-002",
      "k": "ok",
      "m": "All 100 schemas validated",
      "t": "2026-09-21T12:01:10Z"
    }
  ],
  "hermesMeta": {
    "activeCount": 1,
    "completedCount": 2,
    "failedCount": 0,
    "generatedAt": "2026-09-21T12:05:00Z",
    "sessionId": "sess-main-12345"
  },
  "hermesTree": [
    {
      "active_tool": "delegate_task",
      "children": [
        {
          "active_tool": "run_command",
          "children": [],
          "id": "sub-child-001",
          "name": "Lint Checker",
          "role": "ShellCheck and lint passed cleanly",
          "state": "SUCCEEDED"
        },
        {
          "active_tool": "run_command",
          "children": [],
          "id": "sub-child-002",
          "name": "Contract Tester",
          "role": "All 100 schemas validated",
          "state": "SUCCEEDED"
        }
      ],
      "id": "sub-lead-001",
      "name": "Lead Planner",
      "role": "Delegated sub-tasks to child agents",
      "state": "RUNNING"
    }
  ],
  "issues": [
    {
      "a": "epic",
      "n": "#195",
      "s": "open",
      "t": "Epic: implementasi penuh Control Center berbasis AWCMS"
    },
    {
      "a": "foundation",
      "n": "#196",
      "s": "open",
      "t": "Schema, RLS, permission, dan descriptor modul omes_control"
    },
    {
      "a": "foundation",
      "n": "#197",
      "s": "open",
      "t": "Konsumsi kontrak OMES v1 dengan validasi fail-closed"
    },
    {
      "a": "api",
      "n": "#198",
      "s": "open",
      "t": "API owner/operator untuk projeksi dan operasi aman"
    },
    {
      "a": "api",
      "n": "#199",
      "s": "open",
      "t": "Ingestion enrollment, poll, result, dan heartbeat worker"
    },
    {
      "a": "api",
      "n": "#192",
      "s": "open",
      "t": "Transport pull-worker aman untuk GUI web AWCMS-one"
    },
    {
      "a": "ui",
      "n": "#200",
      "s": "design",
      "t": "Layar admin: overview, servers, deployments, operations, jobs"
    },
    {
      "a": "ui",
      "n": "#201",
      "s": "design",
      "t": "Layar health, backup/recovery, dan audit"
    },
    {
      "a": "ui",
      "n": "#183",
      "s": "design",
      "t": "Visualisasi orkestrasi Hermes dan subagent langsung"
    },
    {
      "a": "ui",
      "n": "#211",
      "s": "design",
      "t": "Redesign prototipe Control Center v2 dan data-driven fixtures"
    },
    {
      "a": "release",
      "n": "#202",
      "s": "open",
      "t": "Verifikasi dan penutupan rilis Control Center"
    }
  ],
  "jobsRunning": [
    {
      "host": "srv-0001",
      "id": "job-0001",
      "line": "state: succeeded",
      "name": "backup - srv-0001",
      "pct": 100
    }
  ],
  "kpis": [
    {
      "accent": "ink",
      "foot": "2 domain",
      "label": "Host terkelola",
      "value": "12"
    },
    {
      "accent": "warn",
      "foot": "3 host dari 12",
      "label": "Drift terdeteksi",
      "value": "3"
    },
    {
      "accent": "violet",
      "foot": "menunggu persetujuan owner",
      "label": "Operasi menunggu",
      "value": "1"
    },
    {
      "accent": "ok",
      "foot": "1 dari 2 deployment",
      "label": "Verify lulus",
      "value": "50.0%"
    }
  ],
  "milestones": [
    {
      "done": 2,
      "name": "Control Center and Entitlements",
      "note": "Epic #195 dan turunannya",
      "open": 9,
      "pct": 18
    },
    {
      "done": 6,
      "name": "Quality and Security",
      "note": "#180, #181 - drift review upstream",
      "open": 2,
      "pct": 75
    },
    {
      "done": 14,
      "name": "Core CLI (bootstrap - rollback)",
      "note": "Rilis pre-alpha v0.3.0",
      "open": 0,
      "pct": 100
    },
    {
      "done": 9,
      "name": "Provider coverage",
      "note": "apt, systemd, ufw, caddy, postgres",
      "open": 4,
      "pct": 69
    }
  ],
  "queue": [
    {
      "age": "baru",
      "by": "user:user-jane",
      "id": "corr-op-0001",
      "name": "restart -> server-acme-01",
      "need": "Diizinkan otomatis",
      "risk": "medium"
    }
  ],
  "servers": [
    {
      "agent": "0.3.0",
      "cpu": 52,
      "disk": 63,
      "drift": 3,
      "host": "app-01.jkt.ahliweb.net",
      "id": "omes-app-01",
      "last": "7s",
      "mem": 71,
      "modules": 12,
      "os": "Ubuntu 26.04",
      "role": "AWCMS app",
      "state": "drift",
      "uptime": "18d 22:41"
    },
    {
      "agent": "0.3.0",
      "cpu": 47,
      "disk": 59,
      "drift": 0,
      "host": "app-02.jkt.ahliweb.net",
      "id": "omes-app-02",
      "last": "11s",
      "mem": 66,
      "modules": 12,
      "os": "Ubuntu 26.04",
      "role": "AWCMS app",
      "state": "ok",
      "uptime": "18d 22:39"
    },
    {
      "agent": "0.3.0",
      "cpu": 78,
      "disk": 81,
      "drift": 1,
      "host": "app-03.sgp.ahliweb.net",
      "id": "omes-app-03",
      "last": "14s",
      "mem": 84,
      "modules": 12,
      "os": "Ubuntu 24.04",
      "role": "AWCMS app",
      "state": "warn",
      "uptime": "6d 03:55"
    },
    {
      "agent": "0.3.0",
      "cpu": 8,
      "disk": 88,
      "drift": 0,
      "host": "bak-01.sgp.ahliweb.net",
      "id": "omes-bak-01",
      "last": "13s",
      "mem": 22,
      "modules": 4,
      "os": "Ubuntu 26.04",
      "role": "Backup vault",
      "state": "ok",
      "uptime": "120d 02:17"
    },
    {
      "agent": "0.3.0",
      "cpu": 33,
      "disk": 57,
      "drift": 0,
      "host": "db-01.jkt.ahliweb.net",
      "id": "omes-db-01",
      "last": "6s",
      "mem": 62,
      "modules": 5,
      "os": "Ubuntu 26.04",
      "role": "Postgres 17",
      "state": "ok",
      "uptime": "93d 11:02"
    },
    {
      "agent": "0.3.0",
      "cpu": 21,
      "disk": 57,
      "drift": 0,
      "host": "db-02.jkt.ahliweb.net",
      "id": "omes-db-02",
      "last": "8s",
      "mem": 58,
      "modules": 5,
      "os": "Ubuntu 26.04",
      "role": "Postgres 17 replica",
      "state": "ok",
      "uptime": "93d 10:58"
    },
    {
      "agent": "0.3.0",
      "cpu": 14,
      "disk": 44,
      "drift": 0,
      "host": "edge-01.jkt.ahliweb.net",
      "id": "omes-edge-01",
      "last": "12s",
      "mem": 38,
      "modules": 7,
      "os": "Ubuntu 26.04",
      "role": "Edge / Caddy",
      "state": "ok",
      "uptime": "41d 06:12"
    },
    {
      "agent": "0.3.0",
      "cpu": 11,
      "disk": 41,
      "drift": 0,
      "host": "edge-02.jkt.ahliweb.net",
      "id": "omes-edge-02",
      "last": "9s",
      "mem": 35,
      "modules": 7,
      "os": "Ubuntu 26.04",
      "role": "Edge / Caddy",
      "state": "ok",
      "uptime": "41d 06:10"
    },
    {
      "agent": "0.3.0",
      "cpu": 64,
      "disk": 38,
      "drift": 0,
      "host": "job-01.jkt.ahliweb.net",
      "id": "omes-job-01",
      "last": "4s",
      "mem": 49,
      "modules": 9,
      "os": "Ubuntu 26.04",
      "role": "Hermes worker",
      "state": "ok",
      "uptime": "12d 04:30"
    },
    {
      "agent": "0.3.0",
      "cpu": 58,
      "disk": 36,
      "drift": 0,
      "host": "job-02.sgp.ahliweb.net",
      "id": "omes-job-02",
      "last": "5s",
      "mem": 44,
      "modules": 9,
      "os": "Ubuntu 24.04",
      "role": "Hermes worker",
      "state": "ok",
      "uptime": "12d 04:28"
    },
    {
      "agent": "0.2.8",
      "cpu": 0,
      "disk": 29,
      "drift": 2,
      "host": "build-01.lab.internal",
      "id": "omes-mint-01",
      "last": "2h 14m",
      "mem": 0,
      "modules": 6,
      "os": "Linux Mint 22",
      "role": "Build / lab",
      "state": "stale",
      "uptime": "-"
    },
    {
      "agent": "0.3.0",
      "cpu": 29,
      "disk": 72,
      "drift": 0,
      "host": "obs-01.jkt.ahliweb.net",
      "id": "omes-obs-01",
      "last": "10s",
      "mem": 55,
      "modules": 8,
      "os": "Ubuntu 26.04",
      "role": "Observability",
      "state": "ok",
      "uptime": "41d 05:44"
    }
  ],
  "snapshots": [
    {
      "dur": "-",
      "id": "backup-0001",
      "scope": "srv-0001",
      "size": "0.0 MB",
      "verify": "ok",
      "when": "2026-09-19T10:00:00Z"
    }
  ],
  "timeline": [
    {
      "kind": "rollback",
      "t": "2026-09-19T09:00:05Z",
      "txt": "deployment deployment-acme-hermes-01 -> version 1.5.0",
      "who": "server-acme-01"
    },
    {
      "kind": "ok",
      "t": "2026-09-19T08:00:05Z",
      "txt": "deployment deployment-acme-hermes-01 -> version 1.4.0",
      "who": "server-acme-01"
    },
    {
      "kind": "ok",
      "t": "2026-02-01T00:00:02Z",
      "txt": "payment.succeeded delivery-00000001",
      "who": "provider/provider-primary"
    },
    {
      "kind": "ok",
      "t": "2026-02-01T00:00:00Z",
      "txt": "payment.succeeded evt-payment-succeeded-00000001",
      "who": "svc/outbox"
    }
  ],
  "workers": [
    {
      "host": "srv-prod-01",
      "id": "wrk-srv-prod-01-001",
      "poll": "10s",
      "state": "active",
      "token": "enrolled 2026-09-21T12:00:00Z",
      "ver": "0.1.0"
    }
  ]
};
