import os
import shutil
import tempfile
import unittest

from . import _pathfix  # noqa: F401

from graphify import obsidian  # noqa: E402


class TestPurge(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="omes-graphify-purge-test-")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _write(self, rel, content):
        path = os.path.join(self.tmp, rel)
        os.makedirs(os.path.dirname(path) or self.tmp, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    def test_plan_on_missing_dir_is_empty(self):
        removable, skipped = obsidian.plan_purge_export(os.path.join(self.tmp, "nope"))
        self.assertEqual(removable, [])
        self.assertEqual(skipped, [])

    def test_generated_markdown_is_removable(self):
        self._write("a.md", "---\nomes_generated: true\n---\nbody\n")
        removable, skipped = obsidian.plan_purge_export(self.tmp)
        self.assertEqual(removable, ["a.md"])
        self.assertEqual(skipped, [])

    def test_user_authored_markdown_is_skipped_never_removable(self):
        self._write("my-notes.md", "# my own note\n")
        removable, skipped = obsidian.plan_purge_export(self.tmp)
        self.assertEqual(removable, [])
        self.assertEqual(skipped, ["my-notes.md"])

    def test_non_markdown_file_owned_via_manifest_is_removable(self):
        self._write("graph.canvas", '{"nodes": []}')
        self._write(
            obsidian.OMES_EXPORT_MANIFEST_NAME,
            '{"omes_generated": true, "files": ["graph.canvas"]}',
        )
        removable, skipped = obsidian.plan_purge_export(self.tmp)
        self.assertIn("graph.canvas", removable)
        self.assertNotIn("graph.canvas", skipped)

    def test_non_markdown_file_not_in_manifest_is_skipped(self):
        self._write("unrelated.bin", "not ours")
        self._write(
            obsidian.OMES_EXPORT_MANIFEST_NAME,
            '{"omes_generated": true, "files": []}',
        )
        removable, skipped = obsidian.plan_purge_export(self.tmp)
        self.assertNotIn("unrelated.bin", removable)
        self.assertIn("unrelated.bin", skipped)

    def test_purge_deletes_only_removable_files_and_the_manifest(self):
        self._write("a.md", "---\nomes_generated: true\n---\nbody\n")
        self._write("keep.md", "# not generated by OMES\n")
        self._write("graph.canvas", '{"nodes": []}')
        self._write(
            obsidian.OMES_EXPORT_MANIFEST_NAME,
            '{"omes_generated": true, "files": ["graph.canvas"]}',
        )

        removed, skipped = obsidian.purge_export(self.tmp)

        self.assertIn("a.md", removed)
        self.assertIn("graph.canvas", removed)
        self.assertIn(obsidian.OMES_EXPORT_MANIFEST_NAME, removed)
        self.assertIn("keep.md", skipped)
        self.assertFalse(os.path.exists(os.path.join(self.tmp, "a.md")))
        self.assertFalse(os.path.exists(os.path.join(self.tmp, "graph.canvas")))
        self.assertTrue(os.path.exists(os.path.join(self.tmp, "keep.md")))
        with open(os.path.join(self.tmp, "keep.md"), encoding="utf-8") as f:
            self.assertEqual(f.read(), "# not generated by OMES\n")

    def test_purge_removes_now_empty_subdirectories_but_not_ones_with_kept_files(self):
        self._write("sub/a.md", "---\nomes_generated: true\n---\nbody\n")
        self._write("keep-sub/keep.md", "# not generated by OMES\n")

        obsidian.purge_export(self.tmp)

        self.assertFalse(os.path.isdir(os.path.join(self.tmp, "sub")))
        self.assertTrue(os.path.isdir(os.path.join(self.tmp, "keep-sub")))
        self.assertTrue(os.path.exists(os.path.join(self.tmp, "keep-sub", "keep.md")))

    def test_purge_is_idempotent(self):
        self._write("a.md", "---\nomes_generated: true\n---\nbody\n")
        first_removed, _ = obsidian.purge_export(self.tmp)
        self.assertIn("a.md", first_removed)
        second_removed, second_skipped = obsidian.purge_export(self.tmp)
        self.assertEqual(second_removed, [])
        self.assertEqual(second_skipped, [])


if __name__ == "__main__":
    unittest.main()
