#!/usr/bin/env python3
"""scripts/generate-control-center-data.py - build ui/control-center/data.js
from the Control Center v1 contract fixtures (issue #211).

The Control Center UI prototype (ui/control-center/index.html) is a
reference-only, presentation prototype: the functional screens themselves
are tracked in #200/#201 and are NOT implemented yet. To keep the prototype
honest about where its example numbers come from, its domain data (fleet,
deployments, jobs/operations, health checks, backups, audit events,
workers, and the Hermes orchestration tree/events) is generated - not
hand-typed in the HTML - from:

  1. contracts/control-center/v1/fixtures/*/valid-*.json
     (the same fixtures scripts/check-contracts.py validates against their
     JSON Schemas), and
  2. ui/control-center/sample-fleet.json, a small, clearly-labelled
     supplementary sample file for fleet-level telemetry (CPU/memory/disk,
     OS, agent version, uptime) that has no v1 contract fixture yet.

A handful of sections (the Hermes integration "milestones"/"issues"
roadmap snapshot shown on the Progress screen) have no contract fixture at
all - they describe GitHub issue backlog state, not a runtime contract -
so they are kept as a small, clearly-labelled constant table in this
script (ROADMAP_MILESTONES / ROADMAP_ISSUES below), sourced from the
scratchpad's github.md screen map at authoring time. Update them by hand
when the backlog changes; everything else regenerates automatically.

Usage:
  scripts/generate-control-center-data.py            # write ui/control-center/data.js
  scripts/generate-control-center-data.py --check     # exit 1 if data.js is stale
  scripts/generate-control-center-data.py --out PATH  # write elsewhere (testing)

Output is deterministic: fixtures are read in sorted path order, JSON keys
are sorted, and no wall-clock timestamp is embedded, so two runs against
the same fixtures always produce byte-identical output.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES_ROOT = REPO_ROOT / "contracts" / "control-center" / "v1" / "fixtures"
SAMPLE_FLEET_PATH = REPO_ROOT / "ui" / "control-center" / "sample-fleet.json"
DEFAULT_OUT = REPO_ROOT / "ui" / "control-center" / "data.js"

HEADER = """// ui/control-center/data.js
// AUTO-GENERATED by scripts/generate-control-center-data.py - DO NOT EDIT BY HAND.
//
// Regenerate with:
//   python3 scripts/generate-control-center-data.py
//
// Sourced from contracts/control-center/v1/fixtures/*/valid-*.json (the
// same fixtures scripts/check-contracts.py validates) plus
// ui/control-center/sample-fleet.json (a small supplementary sample for
// fleet telemetry that has no v1 contract fixture yet). See that script's
// module docstring for exactly which fixtures feed which section.
//
// This is reference/prototype data for ui/control-center/index.html
// (issue #211). The functional Control Center screens are NOT
// implemented yet (tracked in #200/#201) - this file only feeds a static
// UI/UX prototype.
"""

# ---------------------------------------------------------------------------
# Roadmap snapshot - no v1 contract fixture backs GitHub issue/milestone
# state, so it is kept here as a small, clearly-labelled constant table.
# Source: the scratchpad github.md screen map (issue #211) and the
# Progress screen of the original design prototype. Update by hand when
# the ahliweb/omes Control Center backlog changes.
# ---------------------------------------------------------------------------
ROADMAP_MILESTONES: list[dict[str, Any]] = [
    {"name": "Control Center and Entitlements", "done": 2, "open": 9, "pct": 18, "note": "Epic #195 dan turunannya"},
    {"name": "Quality and Security", "done": 6, "open": 2, "pct": 75, "note": "#180, #181 - drift review upstream"},
    {"name": "Core CLI (bootstrap - rollback)", "done": 14, "open": 0, "pct": 100, "note": "Rilis pre-alpha v0.3.0"},
    {"name": "Provider coverage", "done": 9, "open": 4, "pct": 69, "note": "apt, systemd, ufw, caddy, postgres"},
]

ROADMAP_ISSUES: list[dict[str, Any]] = [
    {"n": "#195", "t": "Epic: implementasi penuh Control Center berbasis AWCMS", "s": "open", "a": "epic"},
    {"n": "#196", "t": "Schema, RLS, permission, dan descriptor modul omes_control", "s": "open", "a": "foundation"},
    {"n": "#197", "t": "Konsumsi kontrak OMES v1 dengan validasi fail-closed", "s": "open", "a": "foundation"},
    {"n": "#198", "t": "API owner/operator untuk projeksi dan operasi aman", "s": "open", "a": "api"},
    {"n": "#199", "t": "Ingestion enrollment, poll, result, dan heartbeat worker", "s": "open", "a": "api"},
    {"n": "#192", "t": "Transport pull-worker aman untuk GUI web AWCMS-one", "s": "open", "a": "api"},
    {"n": "#200", "t": "Layar admin: overview, servers, deployments, operations, jobs", "s": "design", "a": "ui"},
    {"n": "#201", "t": "Layar health, backup/recovery, dan audit", "s": "design", "a": "ui"},
    {"n": "#183", "t": "Visualisasi orkestrasi Hermes dan subagent langsung", "s": "design", "a": "ui"},
    {"n": "#211", "t": "Redesign prototipe Control Center v2 dan data-driven fixtures", "s": "design", "a": "ui"},
    {"n": "#202", "t": "Verifikasi dan penutupan rilis Control Center", "s": "open", "a": "release"},
]


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def load_fixture(schema_name: str, filename: str = "valid-01.json") -> dict[str, Any]:
    path = FIXTURES_ROOT / schema_name / filename
    return load_json(path)


def load_fixtures(schema_name: str) -> list[dict[str, Any]]:
    """Load every valid-*.json fixture for schema_name, sorted by filename.

    Fails loudly (like load_fixture()) when the fixture directory is
    missing, instead of silently returning an empty list: a renamed or
    removed schema directory must fail the generator (and its --check
    gate), not silently zero out a whole UI section."""
    fixture_dir = FIXTURES_ROOT / schema_name
    if not fixture_dir.is_dir():
        raise FileNotFoundError(f"fixture directory not found: {fixture_dir}")
    return [load_json(p) for p in sorted(fixture_dir.glob("valid-*.json"))]


# ---------------------------------------------------------------------------
# Section builders - each one is intentionally small and documents which
# fixture(s) it reads from.
# ---------------------------------------------------------------------------

def build_servers() -> list[dict[str, Any]]:
    """ui/control-center/sample-fleet.json - fleet telemetry has no v1
    contract fixture yet (see that file's _provenance note)."""
    sample = load_json(SAMPLE_FLEET_PATH)
    servers = sorted(sample["servers"], key=lambda s: s["id"])
    return servers


def build_hermes_tree() -> dict[str, Any]:
    """contracts/.../fixtures/hermes-orchestration-tree/valid-01.json.

    The fixture is a flat list of nodes with parent_subagent_id; this
    nests them into the {id, name, role, children} shape the UI expects.
    """
    fixture = load_fixture("hermes-orchestration-tree")
    nodes_by_id = {n["subagent_id"]: n for n in fixture["nodes"]}

    def to_ui_node(node: dict[str, Any]) -> dict[str, Any]:
        children = [to_ui_node(nodes_by_id[cid]) for cid in node.get("children", []) if cid in nodes_by_id]
        return {
            "id": node["subagent_id"],
            "name": node["role"].replace("_", " ").title(),
            "role": node.get("summary") or node.get("goal", ""),
            "state": node.get("state", ""),
            "active_tool": node.get("active_tool"),
            "children": children,
        }

    root = nodes_by_id.get(fixture.get("root_subagent_id"))
    tree = [to_ui_node(root)] if root else []
    return {
        "tree": tree,
        "session_id": fixture.get("session_id"),
        "generated_at": fixture.get("generated_at"),
        "active_count": fixture.get("active_count", 0),
        "completed_count": fixture.get("completed_count", 0),
        "failed_count": fixture.get("failed_count", 0),
    }


def build_hermes_events(tree_fixture_nodes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """contracts/.../fixtures/hermes-orchestration-event/valid-01.json plus
    the state of every node in the hermes-orchestration-tree fixture -
    each node contributes one deterministic timeline entry so the "Jejak
    eksekusi" list has more than a single row."""
    events: list[dict[str, Any]] = []
    state_to_kind = {"RUNNING": "tool", "SUCCEEDED": "ok", "FAILED": "deny", "PENDING": "wait"}
    for node in tree_fixture_nodes:
        events.append({
            "a": node["subagent_id"],
            "k": state_to_kind.get(node.get("state", ""), "plan"),
            "m": node.get("summary") or node.get("goal", ""),
            "t": node.get("started_at", ""),
        })
    event_fixture = load_fixture("hermes-orchestration-event")
    events.append({
        "a": event_fixture["subagent_id"],
        "k": "tool",
        "m": event_fixture.get("summary", ""),
        "t": event_fixture.get("timestamp", ""),
    })
    events.sort(key=lambda e: e["t"])
    return events


def build_deployments() -> list[dict[str, Any]]:
    """Pairs contracts/.../deployment.request/valid-*.json (who/operation)
    with contracts/.../deployment-view/valid-*.json (state) on their real
    shared key: (target.server_id, target.deployment_id).

    The two fixture families are independently authored and, at present,
    describe entirely different deployments (deployment.request targets
    srv-0001/dep-0001; deployment-view targets server-acme-01/
    deployment-acme-hermes-01) - there is no genuine causal link between
    them. Pairing by sorted-filename index position would therefore
    fabricate actor -> deployment causality (e.g. attributing operator-1's
    restore request to an unrelated rollback view). Instead, only requests
    that share both server_id and deployment_id with a view are attributed
    to it; when no request matches, "who" is the neutral placeholder "-"
    rather than an invented or overly generic actor."""
    requests = load_fixtures("deployment.request")
    views = load_fixtures("deployment-view")
    requests_by_target = {
        (req["target"]["server_id"], req["target"]["deployment_id"]): req
        for req in requests
    }
    rows = []
    for view in views:
        target_key = (view["target"]["server_id"], view["target"]["deployment_id"])
        req = requests_by_target.get(target_key)
        desired = view["desired_state"]
        observed = view["observed_state"]
        in_sync = desired.get("status") == observed.get("status") and desired.get("version") == observed.get("version")
        state = "ok" if in_sync else ("rollback" if view.get("error_evidence") else "run")
        rows.append({
            "id": view["target"]["deployment_id"],
            "mod": "version " + str(desired.get("version")),
            "env": view.get("tenant_id", ""),
            "hosts": view["target"]["server_id"],
            "who": (req["actor"]["type"] + ":" + req["actor"]["id"]) if req else "-",
            "when": view.get("last_reconciled_at", ""),
            "state": state,
            "pct": 100 if in_sync else 60,
        })
    return rows


def build_jobs_and_operations() -> dict[str, Any]:
    """contracts/.../job-status.response/valid-01.json and
    contracts/.../operation-request/valid-01.json."""
    job = load_fixture("job-status.response")
    op = load_fixture("operation-request")
    jobs_running = [{
        "id": job["job_id"],
        "name": job["operation"] + " - " + job.get("target", {}).get("server_id", ""),
        "host": job.get("target", {}).get("server_id", ""),
        "pct": 100 if job.get("state") == "succeeded" else 50,
        "line": "state: " + job.get("state", ""),
    }]
    queue = [{
        "id": op["correlation_id"],
        "name": op["operation"] + " -> " + op["target"].get("server_id", ""),
        "by": op["actor"]["type"] + ":" + op["actor"]["id"],
        "risk": "high" if not op["permission"].get("granted", True) else "medium",
        "need": "Menunggu persetujuan" if op["permission"].get("requires_approval") else "Diizinkan otomatis",
        "age": "baru",
    }]
    return {"jobs_running": jobs_running, "queue": queue}


def build_health() -> list[dict[str, Any]]:
    """contracts/.../health-readiness.response/valid-01.json 'layers'."""
    fixture = load_fixture("health-readiness.response")
    rows = []
    for name, layer in sorted(fixture.get("layers", {}).items()):
        rows.append({
            "name": name.replace("_", " ").title(),
            "res": layer.get("status", ""),
            "detail": layer.get("proves", ""),
        })
    return rows


def build_backups() -> dict[str, Any]:
    """contracts/.../backup-status.response/valid-01.json."""
    fixture = load_fixture("backup-status.response")
    snapshot = {
        "id": fixture["backup_id"],
        "scope": fixture["target"]["server_id"],
        "size": str(round(fixture.get("size_bytes", 0) / (1024 * 1024), 1)) + " MB",
        "when": fixture.get("created_at", ""),
        "verify": "ok" if fixture.get("state") == "completed" else "fail",
        "dur": "-",
    }
    policy = [
        {"k": "Status", "v": fixture.get("state", "")},
        {"k": "Target", "v": fixture["target"]["server_id"]},
        {"k": "Manifest", "v": fixture.get("manifest_sha256", "")[:16] + "..."},
    ]
    return {"snapshots": [snapshot], "policy": policy}


def build_audit() -> list[dict[str, Any]]:
    """contracts/.../outbox-event/valid-01.json and
    contracts/.../webhook-envelope/valid-01.json."""
    outbox = load_fixture("outbox-event")
    webhook = load_fixture("webhook-envelope")
    rows = [
        {
            "t": outbox["occurred_at"],
            "actor": "svc/outbox",
            "role": "system",
            "act": outbox["event_type"],
            "obj": outbox["event_id"],
            "ip": "-",
            "ok": outbox.get("status") != "failed",
        },
        {
            "t": webhook["received_at"],
            "actor": "provider/" + webhook["provider_id"],
            "role": "webhook",
            "act": webhook["event_type"],
            "obj": webhook["delivery_id"],
            "ip": "-",
            "ok": True,
        },
    ]
    rows.sort(key=lambda r: r["t"])
    return rows


def build_workers() -> list[dict[str, Any]]:
    """contracts/.../worker-enrollment.response and
    contracts/.../worker-heartbeat.request valid-01.json fixtures."""
    enrollment = load_fixture("worker-enrollment.response")
    heartbeat = load_fixture("worker-heartbeat.request")
    return [{
        "id": enrollment["worker_id"],
        "host": enrollment["server_id"],
        "state": "active" if heartbeat.get("status") == "healthy" else "stale",
        "poll": str(enrollment.get("poll_interval_seconds", "")) + "s",
        "ver": heartbeat.get("omes_version", ""),
        "token": "enrolled " + enrollment.get("enrolled_at", ""),
    }]


def build_timeline(deployments: list[dict[str, Any]], audit: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Derived from build_deployments()/build_audit() output - no separate
    fixture; this is the Overview screen's "Aktivitas" combined feed."""
    rows = []
    for d in deployments:
        rows.append({"t": d["when"], "who": d["hosts"], "txt": "deployment " + d["id"] + " -> " + d["mod"], "kind": d["state"]})
    for a in audit:
        rows.append({"t": a["t"], "who": a["actor"], "txt": a["act"] + " " + a["obj"], "kind": "ok" if a["ok"] else "err"})
    rows.sort(key=lambda r: r["t"], reverse=True)
    return rows


def build_kpis(servers: list[dict[str, Any]], deployments: list[dict[str, Any]], queue: list[dict[str, Any]]) -> list[dict[str, Any]]:
    host_count = len(servers)
    drift_hosts = sum(1 for s in servers if s.get("drift", 0) > 0)
    ok_deployments = sum(1 for d in deployments if d["state"] == "ok")
    verify_pct = round(100.0 * ok_deployments / len(deployments), 1) if deployments else 0.0
    return [
        {"label": "Host terkelola", "value": str(host_count), "foot": str(len({s['host'].split('.')[-2] if '.' in s['host'] else s['host'] for s in servers})) + " domain", "accent": "ink"},
        {"label": "Drift terdeteksi", "value": str(drift_hosts), "foot": str(drift_hosts) + " host dari " + str(host_count), "accent": "warn"},
        {"label": "Operasi menunggu", "value": str(len(queue)), "foot": "menunggu persetujuan owner", "accent": "violet"},
        {"label": "Verify lulus", "value": str(verify_pct) + "%", "foot": str(ok_deployments) + " dari " + str(len(deployments)) + " deployment", "accent": "ok"},
    ]


def build_data() -> dict[str, Any]:
    servers = build_servers()
    hermes_tree = build_hermes_tree()
    tree_fixture = load_fixture("hermes-orchestration-tree")
    hermes_events = build_hermes_events(tree_fixture["nodes"])
    deployments = build_deployments()
    jobs_ops = build_jobs_and_operations()
    health = build_health()
    backups = build_backups()
    audit = build_audit()
    workers = build_workers()
    timeline = build_timeline(deployments, audit)
    kpis = build_kpis(servers, deployments, jobs_ops["queue"])

    return {
        "servers": servers,
        "hermesTree": hermes_tree["tree"],
        "hermesMeta": {
            "sessionId": hermes_tree["session_id"],
            "generatedAt": hermes_tree["generated_at"],
            "activeCount": hermes_tree["active_count"],
            "completedCount": hermes_tree["completed_count"],
            "failedCount": hermes_tree["failed_count"],
        },
        "hermesEvents": hermes_events,
        "deployments": deployments,
        "jobsRunning": jobs_ops["jobs_running"],
        "queue": jobs_ops["queue"],
        "health": health,
        "backupPolicy": backups["policy"],
        "snapshots": backups["snapshots"],
        "audit": audit,
        "workers": workers,
        "timeline": timeline,
        "kpis": kpis,
        "milestones": ROADMAP_MILESTONES,
        "issues": ROADMAP_ISSUES,
    }


def render(data: dict[str, Any]) -> str:
    body = json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False)
    return HEADER + "window.OMES_CC_DATA = " + body + ";\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed data.js is stale")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output path (default: ui/control-center/data.js)")
    args = parser.parse_args(argv)

    rendered = render(build_data())

    if args.check:
        if not args.out.is_file():
            print(f"generate-control-center-data: {args.out} does not exist; run without --check to create it", file=sys.stderr)
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != rendered:
            print(f"generate-control-center-data: {args.out} is stale; run scripts/generate-control-center-data.py", file=sys.stderr)
            return 1
        print(f"generate-control-center-data: OK ({args.out} is up to date)")
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    print(f"generate-control-center-data: wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
